spring:
  application:
    name: CarApp
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/copyria"
    data:
      mongodb:
        uri: mongodb://localhost:27017/product-db
server:
  port: 8080