
include:
  - path: ./CarApp/docker-compose.yaml
  - path: ./OrderApp/docker-compose.yaml

services:
  app:
    build:
      context: .
    volumes:
      - ./backend:/app
    restart: on-failure
    command: >
        sh -c "java -jar app.jar"