spring:
  application:
    name: OrderApp
  datasource:
    url: jdbc:postgresql://localhost:5432/xxx
    username: postgres
    password: postgres
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate.format_sql: true
    jackson:
      serialization:
        FAIL_ON_EMPTY_BEANS: false
        WRITE-DATES-AS-TIMESTAMPS: false
    liquibase:
      enabled: true
    security:
      oauth2:
        client:
          provider:
            keycloak:
              token-uri: "http://localhost:9090/realms/copyria/protocol/openid-connect/token"
          registration:
            order-service-client:
              authorization-grant-type: client_credentials
              client-id: "order-service-client"
              client-secret: "EGaAO6ennRN5vc5H9nrMCQFF4qU8f967PCCCHs1ojxzB2cmxXhR2DoRTp4qqwcSY"
              provider: keycloak
        resourceserver:
          jwt:
            issuer-uri: "http://localhost:9090/realms/copyria"
  app:
    apis:
      product-service:
        base-url: "http://localhost:8080/"
  server:
    port: 8081