services:
  pg:
    image: postgres:latest
    container_name: pg-local
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "orderDb"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres-keycloak:
    image: postgres:15
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    ports:
      - "9090:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-keycloak
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_IMPORT: /opt/keycloak/data/import/copyria-realm.json
    depends_on:
      - postgres-keycloak
    networks:
      - keycloak-net
    volumes:
      - ./misc/keycloak/copyria-realm.json:/opt/keycloak/data/import/copyria-realm.json
    command: start-dev --import-realm

volumes:
  postgres_data:

networks:
  keycloak-net: